"""initial_migration

Revision ID: 0429a6e70c2b
Revises: 421cc3c5188f
Create Date: 2025-07-01 08:15:52.849421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0429a6e70c2b'
down_revision = '421cc3c5188f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###