"""initial_migration

Revision ID: 04f261aeb265
Revises: 354b8382f2a5
Create Date: 2025-07-01 09:34:27.373391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f261aeb265'
down_revision = '354b8382f2a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###