"""Initial migration

Revision ID: 10b5126004a8
Revises: 21218e1e5b8a
Create Date: 2025-06-27 15:54:44.983012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b5126004a8'
down_revision = '21218e1e5b8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###