"""Initial migration

Revision ID: 21218e1e5b8a
Revises: db2bcfa4b330
Create Date: 2025-06-27 15:42:40.792731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21218e1e5b8a'
down_revision = 'db2bcfa4b330'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###