"""initial_migration

Revision ID: 354b8382f2a5
Revises: bb2aefb17709
Create Date: 2025-07-01 09:26:41.363532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354b8382f2a5'
down_revision = 'bb2aefb17709'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###