"""initial_migration

Revision ID: 37293c06dfcc
Revises: fca9556155a4
Create Date: 2025-07-01 09:15:42.674637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37293c06dfcc'
down_revision = 'fca9556155a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###