"""initial_migration

Revision ID: 3bc8374fa983
Revises: ead22fbcdc19
Create Date: 2025-07-01 09:45:30.556694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc8374fa983'
down_revision = 'ead22fbcdc19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###