"""initial_migration

Revision ID: 4101a121a6dc
Revises: 6bd42607125f
Create Date: 2025-07-01 08:33:04.290487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4101a121a6dc'
down_revision = '6bd42607125f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###