"""initial_migration

Revision ID: 421cc3c5188f
Revises: a2afd5a439a8
Create Date: 2025-07-01 08:15:07.521396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421cc3c5188f'
down_revision = 'a2afd5a439a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###