"""initial_migration

Revision ID: 440893e01fcb
Revises: ddf92ea02c80
Create Date: 2025-07-01 08:39:15.858748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440893e01fcb'
down_revision = 'ddf92ea02c80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###