"""Initial migration

Revision ID: 6bd42607125f
Revises: 8fe0a16251c9
Create Date: 2025-07-01 08:18:02.581817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd42607125f'
down_revision = '8fe0a16251c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###