"""initial_migration

Revision ID: 6d271004fca9
Revises: 4101a121a6dc
Create Date: 2025-07-01 08:34:43.419812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d271004fca9'
down_revision = '4101a121a6dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###