"""Initial migration

Revision ID: 6e31704568bd
Revises: df848c9218f3
Create Date: 2025-06-26 13:39:14.872243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e31704568bd'
down_revision = 'df848c9218f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###