"""initial_migration

Revision ID: 8fe0a16251c9
Revises: ed140ca582a3
Create Date: 2025-07-01 08:17:52.604290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe0a16251c9'
down_revision = 'ed140ca582a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###