"""Initial migration

Revision ID: 922122345b2f
Revises: 440893e01fcb
Create Date: 2025-07-01 08:39:25.851194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922122345b2f'
down_revision = '440893e01fcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###