"""Initial migration

Revision ID: a14b25006e97
Revises: b314fa8c2526
Create Date: 2025-07-01 09:19:42.256453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14b25006e97'
down_revision = 'b314fa8c2526'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###