"""Initial migration

Revision ID: a4cc6f17a5ad
Revises: a5e8f5d6b5a6
Create Date: 2025-06-26 11:38:08.872063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4cc6f17a5ad'
down_revision = 'a5e8f5d6b5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###