"""Add chat sessions support - v2

Revision ID: a5e8f5d6b5a6
Revises: 4b749211f420
Create Date: 2025-06-26 11:32:08.839261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e8f5d6b5a6'
down_revision = '4b749211f420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('session_id', sa.UUID(), nullable=False))
    op.drop_constraint('chat_logs_project_id_fkey', 'chat_logs', type_='foreignkey')
    op.create_foreign_key(None, 'chat_logs', 'chat_sessions', ['session_id'], ['id'])
    op.drop_column('chat_logs', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_logs', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_logs', type_='foreignkey')
    op.create_foreign_key('chat_logs_project_id_fkey', 'chat_logs', 'projects', ['project_id'], ['id'])
    op.drop_column('chat_logs', 'session_id')
    # ### end Alembic commands ###