"""initial_migration

Revision ID: b314fa8c2526
Revises: 37293c06dfcc
Create Date: 2025-07-01 09:19:32.652352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b314fa8c2526'
down_revision = '37293c06dfcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###