"""initial_migration

Revision ID: b7f16e72f118
Revises: a14b25006e97
Create Date: 2025-07-01 09:21:52.827432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f16e72f118'
down_revision = 'a14b25006e97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###