"""initial_migration

Revision ID: bb2aefb17709
Revises: b7f16e72f118
Create Date: 2025-07-01 09:25:09.207493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2aefb17709'
down_revision = 'b7f16e72f118'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###