"""Initial migration

Revision ID: db2bcfa4b330
Revises: 6e31704568bd
Create Date: 2025-06-27 14:34:34.551319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2bcfa4b330'
down_revision = '6e31704568bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###