"""initial_migration

Revision ID: ddf92ea02c80
Revises: 6d271004fca9
Create Date: 2025-07-01 08:37:53.226987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf92ea02c80'
down_revision = '6d271004fca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###