"""Initial migration

Revision ID: df848c9218f3
Revises: a4cc6f17a5ad
Create Date: 2025-06-26 11:38:20.165062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df848c9218f3'
down_revision = 'a4cc6f17a5ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###