"""initial_migration

Revision ID: ead22fbcdc19
Revises: 04f261aeb265
Create Date: 2025-07-01 09:39:16.022142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead22fbcdc19'
down_revision = '04f261aeb265'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###