"""initial_migration

Revision ID: ed140ca582a3
Revises: 0429a6e70c2b
Create Date: 2025-07-01 08:17:00.946912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed140ca582a3'
down_revision = '0429a6e70c2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###